name: Context in Github
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        if: ${{github.repositoryUrl == 'git://github.com/SOHAN-cyber/github-action.git'}}
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        id: test_id
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        if: ${{steps.test_id.outputs.outcome == 'success'}}
        run: echo '${{ toJSON(matrix) }}'
  normal_ci:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run ls command
        run: ls -la 